### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by karthiknmenon** [JaganKaartik/wheel#17]
@JaganKaartik Please work on the following UI issues - 
1. The checkbox for `Contacts` page needs to be center aligned. 

Ref - 
![image](https://user-images.githubusercontent.com/41678651/127054188-bac91ba8-6f3d-4b82-8724-3ac7eb8b81a5.png)

For this, please update `neetoUI` package to the latest version and use a `div` wrapper with `flex` properties. 

2. The vertical spacing between the `SubHeader` and that of the listing tables don't match the design.

**Comment by JaganKaartik** [comment]
I have already fixed the checkbox alignment issue however, I have some deployment issues for my latest PRs. 

The `production` branch is from an earlier commit, I will fix these issues and the vertical spacing.

**Comment by karthiknmenon** [comment]
@JaganKaartik Could you please create a new issue for the error in Heroku Deployment and paste a copy of the deployments logs there?
